### PR TITLE
Implement className prop support.

### PR DESCRIPTION
**Pull request by Zack-Tillotson**
I would like to pass a className to the container, it looks like you forgot about it in your implementation :]

### CODE REVIEW

**Comment by RickWong** [comment]
All non InlineCss props are passed when this.props is assign-merged. So className, or even onClick, is passed through.

**Comment by RickWong** [comment]
Thanks though!

**Comment by RickWong** [comment]
Hey @Zack-Tillotson are you OK with the decision?

**Comment by Zack-Tillotson** [comment]
Sure that's fine, I was looking at an older version of the component :+1:

**Pull request closed without merging**
